version: '3.7'

services:

  # esdb:
  #   container_name: esdb
  #   image: eventstore/eventstore:latest 
  #   ports:
  #     - '2113:2113'
  #     - '1113:1113'
  #   environment:
  #     EVENTSTORE_INSECURE: 'true'
  #     EVENTSTORE_CLUSTER_SIZE: 1
  #     EVENTSTORE_EXT_TCP_PORT: 1113
  #     EVENTSTORE_HTTP_PORT: 2113
  #     EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
  #     EVENTSTORE_RUN_PROJECTIONS: all
  #     EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
  #     EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"

  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: on-failure
  #   ports:
  #     - ${MONGODB_PORT}: 27017

  # postgres:
  #   image: postgres:11.1-alpine
  #   restart: on-failure
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   hostname: zookeeper
  #   container_name: zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  
  # broker:
  #   image: confluentinc/cp-server:latest
  #   hostname: broker
  #   container_name: broker
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
  #     KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
  #     CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
  #     CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
  #     CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  #     CONFLUENT_METRICS_ENABLE: "true"
  #     CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
      
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:latest
  #   hostname: schema-registry
  #   container_name: schema-registry
  #   depends_on:
  #     - zookeeper
  #     - broker
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      
  # kafka-tools:
  #   image: confluentinc/cp-kafka:latest
  #   hostname: kafka
  #   container_name: kafka
  #   command: ["tail", "-f", "/dev/null"]
  #   network_mode: "host"

networks:
  default:
    name: custom-network
