version: '3.7'

services:

  esdb:
    container_name: esdb
    image: eventstore/eventstore:latest 
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_INSECURE: 'true'
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_ENABLE_EXTERNAL_TCP: 'true'
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: "true"
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: "true"

  # mongo:
  #   container_name: mongo
  #   restart: on-failure
  #   image: mongo
  #   ports:
  #     - ${MONGODB_PORT}: 27017
  
  postgres:
  image: postgres:11.1-alpine
  restart: on-failure
  ports:
    - '5432:5432'
  environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # rabbitmq:
  #   container_name: rabbitmq
  #   hostname: rabbitmq
  #   image: rabbitmq:management-alpine
  #   ports:
  #     - '4369:4369'
  #     - '5672:5672'
  #     - '25672:25672'
  #     - '15672:15672'

networks:
  default:
    name: custom-network
